import React from 'react';
import Head from 'next/head';
import LogoContour from '../public/LogoContour.svg'

import Navbar from './Navbar';
import HeroSection from './HeroSection';
import MesTechno from './MesTechno';
import AboutSection from './AboutSection';

export default function Home() {
  return (
    <>
      <Head>
        <title>William De Azevedo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="font-Inter px-5 mx-auto my-10 max-w-7xl">
        <Navbar/>
        <HeroSection/>
        <MesTechno />
        <LogoContour className='absolute top-28 left-0 logo__contour w-screen'/>
        <AboutSection/>
      </main>
      
    </>
  );
}